Repository LSSTDESC/BlendingToolKit, pull requests merged in 2020-08, with the labels that each got.

#43 Setup github actions + codecov
  .github/workflows/config.yml
  README.md
  requirements.txt
Labels: pipeline

#45 Im/refactor multiprocessing
  btk/draw_blends.py
  btk/measure.py
  btk/multiprocess.py
  btk/utils.py
Labels: refactor

#41 Add basic WCS
  btk/create_observing_generator.py
  btk/draw_blends.py
  btk/survey.py
Labels: feature, hack
