Repository LSSTDESC/BlendingToolKit, pull requests merged in 2021-07, with the labels that each got.

#174 Fix multiresolution metrics
  btk/measure.py
  btk/metrics.py
  btk/plot_utils.py
  btk/utils.py
  conf/config.yaml
  notebooks/intro.ipynb
  notebooks/scarlet-measure.ipynb
  tests/test_metrics.py
  tests/test_mr.py
  tests/test_save.py
Labels: Ready for review

#178 Switch order of dictionaries for metrics
  btk/metrics.py
  btk/plot_utils.py
  btk/utils.py
  notebooks/intro.ipynb
  notebooks/scarlet-measure.ipynb
  tests/test_metrics.py
  tests/test_mr.py
  tests/test_save.py
Labels: Ready for review, refactor

#180 Changed metrics default value to NaN
  btk/metrics.py
Labels: Ready for review, refactor

#179 Completing documentation
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  btk/draw_blends.py
  btk/measure.py
  btk/metrics.py
  btk/plot_utils.py
  btk/sampling_functions.py
  btk/survey.py
  docs/source/tutorials.rst
  notebooks/advanced-features.ipynb
  notebooks/cosmos_tutorial.ipynb
  notebooks/custom-tutorial.ipynb
  notebooks/galsim_hub_tutorial.ipynb
  notebooks/intro.ipynb
  notebooks/multi-tutorial.ipynb
  notebooks/scarlet-measure.ipynb
  poetry.lock
  pyproject.toml
  tests/sanitize.cfg
  tests/test_draw.py
  tests/test_group_sampling.py
Labels: docs, refactor

#186 Cleanup Documentation
  .github/workflows/lint.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  README.md
  btk/catalog.py
  btk/create_blend_generator.py
  btk/draw_blends.py
  btk/metrics.py
  btk/plot_utils.py
  btk/sampling_functions.py
  btk/survey.py
  conf/hydra/help/btk_help.yaml
  docs/source/catalog.rst
  docs/source/cli.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/src/btk.draw_blends.rst
  docs/source/tutorials.rst
  docs/source/user_guide.rst
  notebooks/cosmos_tutorial.ipynb
  notebooks/custom-tutorial.ipynb
  notebooks/galsim_hub_tutorial.ipynb
  notebooks/intro.ipynb
  notebooks/multi-tutorial.ipynb
Labels: docs

#210 Fix scarlet measure function failing sometimes
  notebooks/scarlet-measure.ipynb
Labels: bug

#211 Added target measures to custom tutorial
  notebooks/custom-tutorial.ipynb
  notebooks/intro.ipynb
Labels: Ready for review, docs, tutorials

#215 Multiresolution flag
  btk/draw_blends.py
  btk/measure.py
  btk/metrics.py
  notebooks/scarlet-measure.ipynb
Labels: Ready for review, refactor

#219 Add documentation on saving/loading
  docs/source/tutorials.rst
  notebooks/intro.ipynb
Labels: Ready for review
