Repository LSSTDESC/BlendingToolKit, pull requests merged in 2021-03, with the labels that each got.

#105 Update documentation
  .github/workflows/docs.yml
  .github/workflows/test.yml
  .gitignore
  README.md
  btk/catalog.py
  btk/create_blend_generator.py
  btk/draw_blends.py
  btk/sampling_functions.py
  btk/survey.py
  docs-requirements.txt
  docs/source/catalog.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/install.rst
  docs/source/src/btk.catalog.rst
  docs/source/src/btk.config.rst
  docs/source/src/btk.create_blend_generator.rst
  docs/source/src/btk.create_observing_generator.rst
  docs/source/src/btk.draw_blends.rst
  docs/source/src/btk.get_input_catalog.rst
  docs/source/src/btk.measure.rst
  docs/source/src/btk.metrics.rst
  docs/source/src/btk.rst
  docs/source/src/btk.sampling_functions.rst
  docs/source/src/btk.survey.rst
  docs/source/tutorials.rst
  docs/source/user_guide.rst
  notebooks/intro.ipynb
Labels: docs

#110 Im/pip cache again
  .github/workflows/test.yml
  LICENSE
  poetry.lock
  pyproject.toml
Labels: bug, feature

#114 Rework measurement part
  btk/draw_blends.py
  btk/measure.py
  btk/metrics.py
  btk/plot_utils.py
  btk/sampling_functions.py
  btk/survey.py
  docs/source/tutorials.rst
  notebooks/Gaslim_draw.ipynb
  notebooks/intro.ipynb
  tests/test_detection_match.py
  tests/test_measure.py
Labels: feature, refactor

#123 Remove multiprocessing flag
  btk/draw_blends.py
  btk/measure.py
  btk/multiprocess.py
  docs/source/tutorials.rst
  notebooks/intro.ipynb
  tests/test_cosmos.py
  tests/test_draw.py
  tests/test_error_cases.py
  tests/test_measure.py
  tests/test_mr.py
Labels: refactor

#117 Added support for galsim_hub
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  btk/draw_blends.py
  btk/sampling_functions.py
  docs/source/catalog.rst
  docs/source/install.rst
  docs/source/tutorials.rst
  notebooks/galsim_hub_tutorial.ipynb
  poetry.lock
  pyproject.toml
  requirements.txt
  tests/test_galsim_hub.py
Labels: feature
