Repository LSSTDESC/BlendingToolKit, pull requests merged in 2021-06, with the labels that each got.

#151 Added SCARLET notebook
  btk/measure.py
  notebooks/scarlet-measure.ipynb
Labels: Ready for review, feature

#169 New scarlet notebook
  notebooks/scarlet-measure.ipynb
Labels: bug

#150 Rework CLI
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitignore
  btk/__main__.py
  btk/catalog.py
  btk/draw_blends.py
  btk/main.py
  btk/measure.py
  btk/metrics.py
  btk/sampling_functions.py
  btk/survey.py
  conf/__init__.py
  conf/config.yaml
  conf/draw_blends/catsim.yaml
  conf/draw_blends/cosmos.yaml
  conf/draw_blends/galsim_hub.yaml
  conf/hydra/help/btk_help.yaml
  conf/sampling/default.yaml
  conf/sampling/galsim_hub.yaml
  conf/sampling/group_sampling.yaml
  conf/sampling/group_sampling_numbered.yaml
  poetry.lock
  pyproject.toml
  tests/test_main.py
Labels: CLI, Ready for review

#162 Improve plotting
  btk/measure.py
  btk/plot_utils.py
  notebooks/intro.ipynb
  notebooks/scarlet-measure.ipynb
  poetry.lock
  pyproject.toml
  tests/test_metrics.py
Labels: Ready for review
