Repository LSSTDESC/BlendingToolKit, pull requests merged in 2022-11, with the labels that each got.

#386 fix SourceNotVisible exception
  btk/draw_blends.py
Labels: bug

#378 Fixing SCARLET notebook and improving plotting
  btk/plot_utils.py
  notebooks/01b-scarlet-measure.ipynb
Labels: bug, feature

#373 Added fixed aperture flux target measure
  btk/metrics.py
  notebooks/00-intro.ipynb
  notebooks/02b-custom-tutorial.ipynb
Labels: feature
