Repository LSSTDESC/BlendingToolKit, pull requests merged in 2022-01, with the labels that each got.

#249 Fixed noise seed identical over a batch
  btk/draw_blends.py
  tests/test_draw.py
  tests/test_metrics.py
Labels: bug

#251 remove galsim hub and tensorflow temporarily
  .github/workflows/test.yml
  CONTRIBUTING.md
  btk/draw_blends.py
  btk/sampling_functions.py
  conf/config.yaml
  conf/draw_blends/galsim_hub.yaml
  conf/hydra/help/btk_help.yaml
  conf/sampling/galsim_hub.yaml
  docs/source/catalog.rst
  docs/source/cli.rst
  docs/source/install.rst
  docs/source/tutorials.rst
  notebooks/01c-galsim_hub_tutorial.ipynb
  notebooks/README.md
  poetry.lock
  pyproject.toml
  tests/test_galsim_hub.py
Labels: refactor

#254 Separate noises
  btk/draw_blends.py
  docs/source/tutorials.rst
  notebooks/00-intro.ipynb
  notebooks/01a-cosmos_tutorial.ipynb
  notebooks/02a-multi-tutorial.ipynb
  notebooks/02b-custom-tutorial.ipynb
  tests/test_cosmos.py
  tests/test_draw.py
  tests/test_group_sampling.py
  tests/test_metrics.py
  tests/test_mr.py
Labels: bug, Ready for review
